version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: roots-market-backend
    container_name: roots-market-backend
    restart: always

    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
